apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksapp
spec:
  selector:
    matchLabels:
      app: eksapp
  replicas: 2
  template:
    metadata:
      labels:
        app: eksapp
    spec:
      containers:
      - name: eksapp
        image: vdkthakur/todo-app:build-9
        ports:
        - containerPort: 80
